name: Ejecutar Bot FMTO
on:
  schedule:
    - cron: '0 9,15 * * *' # 9:00 y 15:00 todos los días
  workflow_dispatch: # Permite ejecutarlo a mano para probar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4 # Actualizado de v3 a v4
      - name: Configurar Python
        uses: actions/setup-python@v5 # Actualizado de v4 a v5
        with:
          python-version: '3.11' # Versión de Python más moderna
      - name: Instalar dependencias
        run: |
          pip install playwright requests pypdf
          playwright install chromium
      - name: Ejecutar bot
        env:
          FMTO_USER: ${{ secrets.FMTO_USER }}
          FMTO_PASS: ${{ secrets.FMTO_PASS }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py
